# rule identifiers to exclude from running
disabled_rules:
  - line_length
  - trailing_whitespace
  - identifier_name

# paths to ignore during linting. Takes precedence over `included`.
excluded:
  - Pods